# Generated by Django 3.0.6 on 2020-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_titel', models.CharField(max_length=100)),
                ('quiz_beschrijving', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'quizzen',
            },
        ),
    ]
