# Generated by Django 3.0.6 on 2020-05-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0002_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='vraag',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enquete.Quiz'),
        ),
    ]
